# Generated by Django 3.2.10 on 2023-01-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Status',
        ),
    ]
